a17/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView


admin.site.site_title = "A17_WordOfMouth"

urlpatterns = [
    path('', include('wordofmouth.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
]

wordofmouth/urls.py
from django.urls import path

from . import views

app_name = 'wordofmouth'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('recipes/<int:pk>/', views.RecipeDetailView.as_view(), name='recipe_detail'),
    path('recipes/<int:pk>/edit/', views.EditRecipeView.as_view(), name = 'edit_recipe'),
    path('recipes/<int:pk>/fork/', views.ForkRecipeView.as_view(), name = 'fork_recipe'),
    path('recipes/<int:pk>/like', views.LikeView, name = 'like_post'),
    path('recipes/<int:pk>/unlike', views.UnlikeView, name = 'unlike_post'),
    path('recipes/<int:pk>/comment', views.CommentView, name = 'comment_post'),
    path('recipes/<int:pk>/rate', views.RateView, name = 'rate_post'),
    path('recipes/<int:rpk>/comment/<int:cpk>/delete', views.deleteComment, name='deleteComment'),
    path('recipes/<int:rpk>/comment/<int:cpk>/edit', views.editCommentView, name='editCommentView'),
    path('recipes/<int:rpk>/comment/<int:cpk>/enter-edit', views.editComment, name='editComment'),
    path('recipes/<int:rpk>/delete', views.deleteRecipe, name='deleteRecipe'),
    path('add/', views.add_Recipe_View, name='add_recipe'),
    path('your_recipes/', views.YourRecipesView.as_view(), name='your_recipes'),
    path('search_recipes/', views.search_recipes, name='search_recipes'),
]

wordofmouth/models.py
########################################################################################
# REFERENCES
#  Title: django-googledrive-storage documentation
#  Author: Gian Luca Dalla Torre and individual contributors
#  Date: 11/28/2021
#  Date Cited: 5/02/2022
#  Code version: 1.6.0
#  URL: https://django-googledrive-storage.readthedocs.io/en/latest/
#  Software License: BSD-3-Clause License
#
#  Title: django-polymorphic documentation
#  Author: Chris Glass, Diederik van der Boor, Charlie Denton,
#          Jerome Leclanche, and individual contributors
#  Date: 11/18/2021
#  Date Cited: 5/03/2022
#  Code version: 3.1
#  URL: https://django-polymorphic.readthedocs.io/en/stable/
#  Software License: BSD-3-Clause License
#
#  Title: Django documentation
#  Author: Django Software Foundation and individual contributors
#  Date: 2021
#  Date Cited: 5/03/2022
#  Code version: 4.0
#  URL (1): https://docs.djangoproject.com/en/4.0/intro/
#  URL (2): https://docs.djangoproject.com/en/4.0/ref/models/fields/#django.db.models.ManyToManyField
#  Software License: BSD-3-Clause License
#
#  Title: Stack Overflow answer to “Using Pre_delete Signal in django”
#  Author: Josh Smeaton (https://stackoverflow.com/users/10583/josh-smeaton)
#  Date: 12/13/2012
#  Date Cited: 5/02/2022
#  URL: https://stackoverflow.com/questions/13857007/using-pre-delete-signal-in-django
#  Software License: CC BY-SA 3.0
#
########################################################################################

'''
  This file follows the structure of the Django tutorial from
  the 'Django documentation' and adapts multiple methods from
  the tutorial
'''

from django.db import models
from django.utils import timezone
from django.contrib import admin
from django.contrib.auth.models import User
from django.db.models.signals import pre_delete
from django.dispatch import receiver

from polymorphic.models import PolymorphicModel
from gdstorage.storage import GoogleDriveStorage


'''
  Define Google Drive Storage using the
  django-googledrive-storage library, for which the
  documentation can be found at the URL at the top
  of this document.
'''
gd_storage = GoogleDriveStorage()

# Create your models here.

class Recipe(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length = 150)
    intro = models.CharField(max_length = 600)
    time = models.DurationField()
    
    '''
      ManyToManyField relationships sourced from the 'Django documentation'
    '''
    likes = models.ManyToManyField(User, related_name='likes', blank=True)
    parent = models.ManyToManyField('self', blank=True, symmetrical=False)
    children = models.ManyToManyField('self', related_name='child', blank=True, symmetrical=False)

    def calc_rating(self):
        ratings = [rate.rating for rate in self.rating_set.all()]
        return sum(ratings)/len(ratings) if ratings else 0

'''
  Handle deleting Recipe objects by defining a reciever for the pre_delete
  signal and manually deleting recipeBlocks to avoid ForeignKey errors
  caused by PolymorphicModel. Also maintains fork history. Sourced from
  a Stack Overflow question answered by user Josh Smeaton. 
'''
@receiver(pre_delete, sender=Recipe, dispatch_uid='recipe_delete_signal')
def onRecipeDelete(sender, instance, using, **kwargs):
    # delete polymorphic elements (avoids ForeignKey errors)
    recipeBlocks = instance.recipeblock_set.all()
    for recipeBlock in recipeBlocks:
        recipeBlock.delete()
    # preserve fork ancestry
    children = instance.children.all()
    if children:
        parents = instance.parent.all()
        for child in children:
            child.parent.set(instance.parent.all())
            if parents:
                parents[0].children.add(child)

class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    commentText = models.CharField(max_length = 4000)
    postTime = models.TimeField(auto_now_add=True)
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)

class Rating(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    rating = models.IntegerField(default=0)
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)

'''
  Define a polymorphic RecipeBlock object using the
  django-polymorphic library, for which the documentation 
  can be found at the URL at the top of this document.
'''
class RecipeBlock(PolymorphicModel):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    isIngredient = isStep = isImage = False

'''
  The following classes inherit from the RecipeBlock
  object using the django-polymorphic library, for
  which the documentation can be found at the URL at
  the top of this document.
'''
class Ingredient(RecipeBlock):
    name = models.CharField(max_length = 150)
    quantity = models.CharField(max_length = 150)
    unit = models.CharField(max_length = 150)
    isIngredient = True

class Step(RecipeBlock):
    text = models.CharField(max_length = 4000)
    isStep = True

'''
  Uses Google Drive Storage as a storage location
  through the django-googledrive-storage library,
  for which the documentation can be found at the
  URL at the top of this document.
'''
class Image(RecipeBlock):
    src = models.ImageField(upload_to='img', storage=gd_storage)
    isImage = True

wordofmouth/views.py
########################################################################################
#  REFERENCES
#  Title: Build A Blog Comment Section - Django Blog #33
#  Author: John Elder
#  Date: 7/16/2020
#  Date Cited: 3/20/2022
#  URL: https://www.youtube.com/watch?v=hZrlh4qU4eQ
#  Software License: Copyright of Codemy.com
#
#  Title: Django documentation
#  Author: Django Software Foundation and individual contributors
#  Date: 2021
#  Date Cited: 5/3/2022
#  Code version: 4.0
#  URL: https://docs.djangoproject.com/en/4.0/intro/
#  Software License: BSD-3-Clause License
#
#  Title: Stack Overflow answer to “Django filter many-to-many with contains”
#  Author: mouad (https://stackoverflow.com/users/479633/mouad)
#  Date: 12/22/2010
#  Date Cited: 5/3/2022
#  URL: https://stackoverflow.com/questions/4507893/django-filter-many-to-many-with-contains
#  Software License: CC BY-SA 2.5
#
########################################################################################

'''
  This file follows the structure of the Django tutorial from
  the 'Django documentation' and adapts multiple methods from
  the tutorial
'''

from urllib import request
from django.dispatch import receiver
from django.views import generic
from django.shortcuts import get_object_or_404, render
from .models import Recipe, RecipeBlock, Ingredient, Step, Image, Comment, Rating
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.db import models
from django.contrib.auth.models import User
import urllib.request
from datetime import timedelta
from django.db.models.query_utils import Q


# view for home page to feed recipe objects to html to show as a list 
class IndexView(generic.ListView):
    template_name = 'wordofmouth/index.html'
    context_object_name = 'recList'

    def get_queryset(self):
        return Recipe.objects.all()


# function for adding like to a recipe
def LikeView(request, pk):
    # get object from db 
    curRecipe = get_object_or_404(Recipe, pk=request.POST.get('input_id'))
    # add user to recipe many to many relationship 
    curRecipe.likes.add(request.user)
    # save the edit 
    curRecipe.save()
    return HttpResponseRedirect(reverse('wordofmouth:recipe_detail', args=(str(pk),)))


# similar idea as LikeView but instead remove the like
def UnlikeView(request, pk):
    curRecipe = get_object_or_404(Recipe, pk=request.POST.get('input_id'))
    curRecipe.likes.remove(request.user)
    curRecipe.save()
    return HttpResponseRedirect(reverse('wordofmouth:recipe_detail', args=(str(pk),)))


def CommentView(request, pk):
    # https://www.youtube.com/watch?v=hZrlh4qU4eQ source for implementing comment section 
    curRecipe = get_object_or_404(Recipe, pk=request.POST.get('comment'))
    curCommentText = request.POST.get('comment_text')
    curComment = Comment(user=request.user, commentText=curCommentText, recipe=curRecipe)

    # avoid posting empty comment 
    if len(curCommentText) != 0:
        curComment = Comment(user=request.user, commentText=curCommentText, recipe=curRecipe)
        curComment.save()

    return HttpResponseRedirect(reverse('wordofmouth:recipe_detail', args=(str(pk),)))


def RateView(request, pk):
    curRecipe = get_object_or_404(Recipe, pk=request.POST.get('rate'))
    curRateNum = request.POST.get('rate_num')
    try:
        curRate = Rating.objects.get(user=request.user, recipe=curRecipe)
        curRate.rating = curRateNum
    except Rating.DoesNotExist:
        curRate = Rating(user=request.user, rating=curRateNum, recipe=curRecipe)
    curRate.save()

    return HttpResponseRedirect(reverse('wordofmouth:recipe_detail', args=(str(pk),)))


class RecipeDetailView(generic.DetailView):
    model = Recipe
    template_name = 'wordofmouth/recipe_detail.html'

# view for home page to feed recipe objects to html to show as a list
class YourRecipesView(generic.ListView):
    template_name = 'wordofmouth/your_recipes.html'
    context_object_name = 'recList'

    def get_queryset(self):
        queryset = {}
        if not self.request.user.is_anonymous:
            userRecipes = Recipe.objects.filter(user=self.request.user)
            
            '''
              Filtering by contents of ManyToManyField contents based on
              a Stack Overflow answer by user mouad
            '''
            likedRecipes = Recipe.objects.filter(likes__in=[self.request.user])

            queryset = {
                'user_recipes': userRecipes,
                'liked_recipes': likedRecipes
            }
        return queryset

def getRecipeData(post, files):
    getTitle = post["Title"]
    getIntro = post["Intro"]
    getTime = timedelta(
        days=int(post["Time[days]"]) if post["Time[days]"] else 0,
        hours=int(post["Time[hours]"] if post["Time[hours]"] else 0),
        minutes=int(post["Time[minutes]"] if post["Time[minutes]"] else 0),
        seconds=int(post["Time[seconds]"] if post["Time[seconds]"] else 0),
    )
    getSteps = post.getlist("Step[]")
    getImages = files.getlist("Image[]")
    getSavedUrls = post.getlist("OldImg[]")
    getImageEntries = post.getlist("Entry[]")
    getIngredients = zip(post.getlist("Ingredient[]"),
                         post.getlist("Quantity[]"),
                         post.getlist("Unit[]"))
    
    return {
        'title': getTitle,
        'intro': getIntro,
        'time': getTime,
        'ingredients': getIngredients,
        'steps': getSteps,
        'images': getImages,
        'savedUrls': getSavedUrls,
        'imageEntries': getImageEntries,
    }


def setRecipeData(userRecipe, rData):
    for ingredient in rData['ingredients']:
        if ingredient[0]:
            Ingredient.objects.create(
                recipe=userRecipe,
                name=ingredient[0],
                quantity=ingredient[1],
                unit = ingredient[2],
            )
    for step in rData['steps']:
        if step:
            Step.objects.create(recipe=userRecipe, text=step)
    for entry in rData['imageEntries']:
        if entry[0] == '1':
            Image.objects.create(recipe=userRecipe, src=rData['images'].pop(0))
        elif entry[1] == '1':
            Image.objects.create(recipe=userRecipe, src=rData['savedUrls'][0])
        rData['savedUrls'].pop(0)


def add_Recipe_View(request):
    if request.POST:
        rData = getRecipeData(request.POST, request.FILES)
        userRecipe = Recipe.objects.create(
            title=rData['title'],
            intro=rData['intro'],
            time=rData['time'],
            user=request.user
        )
        setRecipeData(userRecipe, rData)
        return HttpResponseRedirect(reverse('wordofmouth:recipe_detail', args=(userRecipe.id,)))
    return render(request, "wordofmouth/add_recipe.html")


class EditRecipeView(generic.DetailView):
    model = Recipe
    template_name = 'wordofmouth/edit_recipe.html'

    def post(self, request, *args, **kwargs):
        rData = getRecipeData(request.POST, request.FILES)
        
        userRecipe = self.get_object()
        userRecipe.title = rData['title']
        userRecipe.intro = rData['intro']
        userRecipe.time = rData['time']
        userRecipe.save()
        
        recipeBlocks = userRecipe.recipeblock_set.all()
        for recipeBlock in recipeBlocks:
            recipeBlock.delete()
        
        setRecipeData(userRecipe, rData)
        return HttpResponseRedirect(reverse('wordofmouth:recipe_detail', args=(userRecipe.id,)))


class ForkRecipeView(generic.DetailView):
    model = Recipe
    template_name = 'wordofmouth/edit_recipe.html'

    def post(self, request, *args, **kwargs):
        rData = getRecipeData(request.POST, request.FILES)
        parentRecipe = self.get_object()
        userRecipe = Recipe.objects.create(
            title=rData['title'],
            intro=rData['intro'],
            time=rData['time'],
            user=request.user
        )
        userRecipe.parent.add(parentRecipe)
        parentRecipe.children.add(userRecipe)
        userRecipe.save()
        
        setRecipeData(userRecipe, rData)
        return HttpResponseRedirect(reverse('wordofmouth:recipe_detail', args=(userRecipe.id,)))

def search_recipes(request):
    args = {}
    if request.method == "POST":
        searched = request.POST['searched']
        args = {
            'searched': searched,
            'recipes': Recipe.objects.filter(
                Q(title__icontains=searched) |
                Q(intro__icontains=searched)
            ),
        }
    return render(request, 'wordofmouth/search_recipes.html', args)

def deleteComment(request, rpk, cpk):
    curComment = Comment.objects.filter(pk=request.POST.get('commentPK'))
    curComment.delete()
    return HttpResponseRedirect(reverse('wordofmouth:recipe_detail', args=(rpk,)))

def editCommentView(request, rpk, cpk):
    recipe = Recipe.objects.get(pk = rpk)
    curComment = Comment.objects.get(user=request.user, recipe=recipe, pk=cpk).commentText
    context = {"comment":curComment, 'rpk':rpk, 'cpk':cpk}
    return render(request, 'wordofmouth/edit_comment_view.html', context)

def editComment(request, rpk, cpk):
    curRecipe = get_object_or_404(Recipe, pk=rpk)
    curComment = Comment.objects.get(user=request.user, recipe=curRecipe, pk=cpk)
    # avoid posting empty comment 
    curCommentText = request.POST.get('comment_text')
    if len(curCommentText) != 0:
        curComment.commentText = curCommentText
        curComment.save()

    return HttpResponseRedirect(reverse('wordofmouth:recipe_detail', args=(rpk,)))

def deleteRecipe(request, rpk):
    curRecipe = get_object_or_404(Recipe, pk=rpk)
    curRecipe.delete()
    return HttpResponseRedirect(reverse('wordofmouth:index'))

wordofmouth/templates/wordofmouth/add_recipe.html
{% extends "wordofmouth/base-auth.html" %}

{% block content %}
<h1>Share your recipe:</h1>
{% with mode_='add' %}
{% include "wordofmouth/renderers/recipe_editor/main.html" %}
{% endwith %}
{% endblock %}

wordofmouth/templates/wordofmouth/bootstrap.html
<title>A17 WordOfMouth</title>
{% extends "bootstrap5/bootstrap5.html" %}
{% comment %}<!--
/***************************************************************************************
*  REFERENCES
*  Title: Bootstrap 4 Documentation
*  Author: The Bootstrap team and contributors
*  Date: 2019
*  Date Cited: 4/30/2022
*  Code version: 4.3
*  URL: https://getbootstrap.com/docs/4.3/getting-started/introduction/
*  Software License: MIT License
*
*  Title: Bootstrap 5 Documentation
*  Author: The Bootstrap team and contributors
*  Date: 2021
*  Date Cited: 4/30/2022
*  Code version: 5.1.3
*  URL (1):  https://getbootstrap.com/docs/5.0/components/tooltips/
*  URL (2):  https://getbootstrap.com/docs/5.0/utilities/spacing/
*  URL (3):  https://getbootstrap.com/docs/5.0/components/buttons/
*  URL (4):  https://getbootstrap.com/docs/5.0/layout/grid/
*  URL (5):  https://getbootstrap.com/docs/5.0/utilities/flex/
*  URL (6):  https://getbootstrap.com/docs/5.0/forms/form-control/
*  URL (7):  https://getbootstrap.com/docs/5.0/utilities/text/
*  URL (8):  https://getbootstrap.com/docs/5.0/utilities/shadows/
*  URL (9):  https://getbootstrap.com/docs/5.0/utilities/borders/
*  URL (10): https://getbootstrap.com/docs/5.0/utilities/background/
*  Software License: MIT License
*
*  Title: django-bootstrap-icons
*  Author: Christian Wiegand
*  Date: 2022
*  Date Cited: 4/30/2022
*  Code version: 0.7.5
*  URL: https://github.com/christianwgd/django-bootstrap-icons
*  Software License: MIT License
*
*  Title: Building a Django Web App
*  Author: Ordinary Coders
*  Date: 2020
*  Date Cited: 4/26/2022
*  URL: https://ordinarycoders.com/django-bootstrap
*  Software License: Copyright 2022 Ordinary Media, LLC
*
*  Title: MD Bootstrap 4 Documentation
*  Author: MDB documentation writers
*  Date: 2020
*  Date Cited: 4/26/2022
*  URL: https://mdbootstrap.com/docs/b4/jquery/navigation/footer/
*  Software License: MIT License
*
*  Title: User Registration in Django using Google OAuth
*  Author: Geoffrey Mungai
*  Date: 12/18/2020
*  Date Cited: 4/30/2022
*  URL: https://github.com/section-engineering-education/engineering-education/blob/master/content/articles/django-google-oauth/index.md
*  Software License: Apache-2.0 License
*
***************************************************************************************/
-->{% endcomment %}

{% comment %}<!--
  Where they occur in this document, uses of Bootstrap
  style classes for spacing (margin, padding), layouts
  (flex, grid, img-fluid), justification and alignment,
  buttons, forms, and graphical effects (shadow, rounded,
  border, colors) were sourced from the "Bootstrap 5
  Documentation" at the relevant URLs listed at the top of
  this document. Due to their ubiquitous use throughout
  this project, individual uses of these classes shall not
  be cited explicitly in an attempt to preserve readability.
-->{% endcomment %}

{% comment %}<!--
  This document makes use of Bootstrap icons by means of
  the "django-bootstrap-icons" library and its associated
  template tags, the documentation of which can be found
  at the relevant URL listed at the top of this document.
-->{% endcomment %}

{% load bootstrap5 %}
{% load socialaccount %}
{% load bootstrap_icons %}

{% block bootstrap5_content %}
<html>
  <head>
    {% comment %}<!--
      Include Bootstrap 4.3 JavaScript dependancies, as listed by
      'Bootstrap 4.3 Documentation' (Bootstrap 5.0 JS not working
      properly with tooltips for unknown reasons)
 -->{% endcomment %}
    <script
      src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" 
      crossorigin="anonymous">
    </script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js"
      integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" 
      crossorigin="anonymous">
    </script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js"
      integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" 
      crossorigin="anonymous">
    </script>
  </head>
  
  <body style="background-color:#FFDDAA;">
    {% comment %}<!--
      The following navbar was adapted from code found on
      ordinarycoders.com as part of a Django educational
      course entitled "Building a Django Web App." 
 -->{% endcomment %}
    <nav class="navbar navbar-expand-sm navbar-light bg-light shadow mb-3 px-3">
      <a class="navbar-brand" href="{% url "wordofmouth:index" %}">Home</a>
      <button
        class="navbar-toggler m-3"
        type="button"
        data-toggle="collapse"
        data-target="#navbarText"
        aria-controls="navbarText"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            {% comment %}<!--
              The following authentication template tag and login link,
              as well as all future occurances of these elements in
              this document, are sourced from "User Registration in
              Django usingGoogle OAuth," an educational article
              published as part of Section.io"s Engineering Education
              Program.
         -->{% endcomment %}
            <a
              class="nav-link"
              {% if user.is_authenticated %}
              href="{% url "wordofmouth:your_recipes" %}"
              {% else %}
              href="{% provider_login_url "google" %}"
              {% endif %}
            >
              Your Recipes
            </a>
          </li>
          <li class="nav-item">
            <a
              class="nav-link"
              {% if user.is_authenticated %}
              href="{% url "wordofmouth:add_recipe" %}"
              {% else %}
              href="{% provider_login_url "google" %}"
              {% endif %}
            >
              Add Recipe
            </a>
          </li>
        </ul>
      </div>
      <ul class="navbar-nav ml-auto">
        <li>
          <form class="d-flex" method=POST action="{% url "wordofmouth:search_recipes" %}">
            {% csrf_token %}
            <input
              class="form-control me-2"
              type="search"
              placeholder="Search Recipes"
              aria-label="Search"
              name="searched"
            >
            <button class="btn btn-outline-secondary" type="submit">Search</button>
          </form>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href={% url "account_logout" %}>Log Out</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% provider_login_url "google" %}">Log In With Google</a>
        </li>
        {% endif %}
      </ul>
    </nav>

    <div class="container">
      <center>
        {% block auth %}{% endblock %}
      </center>
    </div>
    
    {% comment %}<!--
      The following footer code was adapted from the "MD
      Bootstrap 4 Documentation", including the basic 
      structure of the footer and style classes. The
      relevant URL is listed in the References section at
      the top of this document.
 -->{% endcomment %}
    <footer class="page-footer pt-4 pb-2 px-2">
      <div class="border p-5 mb-0 bg-light shadow">
        <div class="container">
          <div class="row">
            <div class="col-sm text-left">
              <h6>Meet the creators</h6>
              <a href="https://www.linkedin.com/in/peter-george-6a19601ab/">
                {% bs_icon "linkedin" %} Peter George
              </a>
              <br>
              <a href="https://www.linkedin.com/in/anna-c-alberti/">
                {% bs_icon "linkedin" %} Anna Alberti
              </a>
              <br>
              <a href="https://www.linkedin.com/in/siyang-sun-076592191/">
                {% bs_icon "linkedin" %} Siyang Sun
              </a>
              <br>
              <a href="https://www.linkedin.com/in/ryan-steele-4192b2235/">
                {% bs_icon "linkedin" %} Ryan Steele
              </a>
              <br>
              <a href="https://www.linkedin.com/in/allie-batchvarova-896937191/">
                {% bs_icon "linkedin" %} Allie Batchvarova
              </a> 
            </div>
            <div class="col-sm text-center">
              <h6>About the project:</h6>
              As a project for Advanced Software Development,
              these UVA students set out to create Word of Mouth–a user-friendly,
              convenient, and safe space to share recipes and learn from others.
            </div>
          </div>
        </div>
        <div class="footer-copyright text-center py-3">© 2022 Copyright: A-17 & Co.</div>
      </div>
    </footer>
  </body>
  <script>
      /* 
        Enable all tooltips using code provided by the
        'Bootstrap 5 Documentation,' for which a URL
        can be found at the top of this document.
      */
      var tooltipTriggerList = [].slice.call(
          document.querySelectorAll("[data-bs-toggle='tooltip']")
      );
      var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
          return new bootstrap.Tooltip(tooltipTriggerEl, {
              trigger: "hover",
              placement: "top",
          })
      });
  </script>
</html>
{% endblock %}

wordofmouth/templates/wordofmouth/edit_comment_view.html
{% extends "wordofmouth/base-auth.html" %}
{% comment %}<!--
/***************************************************************************************
*  REFERENCES
*  Title: Bootstrap 5 Documentation
*  Author: The Bootstrap team and contributors
*  Date: 2021
*  Date Cited: 4/30/2022
*  Code version: 5.1.3
*  URL (1): https://getbootstrap.com/docs/5.0/components/buttons/
*  URL (2): https://getbootstrap.com/docs/5.0/forms/form-control/
*  Software License: MIT License
*
***************************************************************************************/
-->{% endcomment %}

{% comment %}<!--
  Where they occur in this document, uses of Bootstrap
  style classes for spacing (margin, padding), layouts
  (flex, grid, img-fluid), justification and alignment,
  buttons, forms, and graphical effects (shadow, rounded,
  border, colors) were sourced from the 'Bootstrap 5
  Documentation' at the relevant URLs listed at the top of
  this document. Due to their ubiquitous use throughout
  this project, individual uses of these classes shall not
  be cited explicitly in an attempt to preserve readability.
-->{% endcomment %}

{% block content %}
<h1>Edit Your Comment</h1>
<form action="{% url 'wordofmouth:editComment' rpk cpk %}" method="post">
  {% csrf_token %}
  <textarea class="form-control" rows="3" name="comment_text">{{ comment }}</textarea>
<button type="submit", name="comment", value="1" class="btn btn-primary">Save</button>
</form>
{% endblock %}

wordofmouth/templates/wordofmouth/edit_recipe.html
{% extends "wordofmouth/base-auth.html" %}

{% block content %}
<h1>Share your recipe:</h1>
{% with mode_='edit' %}
{% include "wordofmouth/renderers/recipe_editor/main.html" %}
{% endwith %}
{% endblock %}